import type { Job } from '../types/job'
import { format, subDays } from 'date-fns'

/**
 * Helper to create a date string N days ago from now.
 */
function daysAgo(n: number): string {
  return format(subDays(new Date(), n), 'yyyy-MM-dd')
}

/**
 * 20 mock jobs with varied statuses, ATS, dates, events, and edge cases.
 */
export const MOCK_JOBS: Job[] = [
  // 1. Submitted 30 days ago, no events — should be detected as ghost
  {
    id: 'job-001',
    date: daysAgo(30),
    status: 'submitted',
    role: 'Senior Product Designer',
    company: 'GhostCorp',
    location: 'Remote',
    salary: '90k',
    ats: 'Greenhouse',
    cv: 'cvflo.pdf',
    portfolio: 'https://floriangouloubi.com',
    link: 'https://ghostcorp.com/jobs/1',
    notes: 'Applied with cover letter motivation',
    source: 'auto',
    area: 'apac',
    events: [],
  },
  // 2. Submitted 50 days ago, no events — high ghost probability
  {
    id: 'job-002',
    date: daysAgo(50),
    status: 'submitted',
    role: 'UX Designer',
    company: 'GhostCorp',
    location: 'Singapore',
    salary: '',
    ats: 'Greenhouse',
    cv: 'cvflo.pdf',
    portfolio: '',
    link: 'https://ghostcorp.com/jobs/2',
    notes: '',
    source: 'auto',
    area: 'apac',
  },
  // 3. Submitted 10 days ago — too recent for ghost
  {
    id: 'job-003',
    date: daysAgo(10),
    status: 'submitted',
    role: 'Product Designer',
    company: 'FreshStartup',
    location: 'Bangkok',
    salary: '80k',
    ats: 'Lever',
    cv: 'cvflo.pdf',
    portfolio: 'https://floriangouloubi.com',
    link: 'https://freshstartup.com/jobs/3',
    notes: 'Great opportunity, cover letter submitted',
    source: 'manual',
    area: 'apac',
    events: [],
  },
  // 4. Submitted 25 days ago WITH events — has response, not ghost
  {
    id: 'job-004',
    date: daysAgo(25),
    status: 'submitted',
    role: 'UI Designer',
    company: 'ActiveCo',
    location: 'Tokyo',
    salary: '100k',
    ats: 'Greenhouse',
    cv: 'cvflo.pdf',
    portfolio: 'https://floriangouloubi.com',
    link: 'https://activeco.com/jobs/4',
    notes: 'Had initial call',
    source: 'auto',
    area: 'apac',
    events: [
      {
        id: 'evt-001',
        date: daysAgo(20),
        type: 'email',
        person: 'HR Manager',
        notes: 'Follow-up received',
        outcome: 'aligned',
        createdAt: daysAgo(20),
      },
    ],
  },
  // 5. Screening status — responded, not ghost
  {
    id: 'job-005',
    date: daysAgo(15),
    status: 'screening',
    role: 'Design Lead',
    company: 'ScreeningInc',
    location: 'Remote',
    salary: '120k',
    ats: 'Lever',
    cv: 'cvflo.pdf',
    portfolio: 'https://floriangouloubi.com',
    link: 'https://screeninginc.com/jobs/5',
    notes: '',
    source: 'auto',
    area: 'emea',
    lastContactDate: daysAgo(10),
  },
  // 6. Interviewing
  {
    id: 'job-006',
    date: daysAgo(20),
    status: 'interviewing',
    role: 'Senior UX Designer',
    company: 'BigTech',
    location: 'Seoul',
    salary: '130k',
    ats: 'Greenhouse',
    cv: 'cvflo.pdf',
    portfolio: 'https://floriangouloubi.com',
    link: 'https://bigtech.com/jobs/6',
    notes: 'Great culture fit, cover letter included',
    source: 'manual',
    area: 'apac',
    events: [
      {
        id: 'evt-002',
        date: daysAgo(14),
        type: 'interview',
        person: 'Design Director',
        notes: 'First round interview',
        outcome: 'aligned',
        createdAt: daysAgo(14),
      },
    ],
  },
  // 7. Rejected
  {
    id: 'job-007',
    date: daysAgo(35),
    status: 'rejected',
    role: 'Product Designer',
    company: 'RejectCorp',
    location: 'Dubai',
    salary: '95k',
    ats: 'Workable',
    cv: 'cvflo.pdf',
    portfolio: 'https://floriangouloubi.com',
    link: 'https://rejectcorp.com/jobs/7',
    notes: 'Rejection after screening',
    source: 'auto',
    area: 'emea',
    lastContactDate: daysAgo(28),
  },
  // 8. Offer
  {
    id: 'job-008',
    date: daysAgo(40),
    status: 'offer',
    role: 'Staff Designer',
    company: 'OfferHQ',
    location: 'Melbourne',
    salary: '150k',
    ats: 'Lever',
    cv: 'cvflo.pdf',
    portfolio: 'https://floriangouloubi.com',
    link: 'https://offerhq.com/jobs/8',
    notes: 'Offer received, negotiating',
    source: 'manual',
    area: 'apac',
    events: [
      {
        id: 'evt-003',
        date: daysAgo(30),
        type: 'interview',
        person: 'VP Design',
        notes: 'Final round',
        outcome: 'aligned',
        createdAt: daysAgo(30),
      },
      {
        id: 'evt-004',
        date: daysAgo(20),
        type: 'offer',
        person: 'HR',
        notes: 'Offer letter sent',
        outcome: 'aligned',
        createdAt: daysAgo(20),
      },
    ],
  },
  // 9. Manual (to submit) — should be excluded from ghost/ATS stats
  {
    id: 'job-009',
    date: daysAgo(5),
    status: 'manual',
    role: 'Visual Designer',
    company: 'ManualCo',
    location: 'Remote',
    salary: '',
    ats: 'Teamtailor',
    cv: '',
    portfolio: '',
    link: 'https://manualco.com/jobs/9',
    notes: '',
    source: 'manual',
    area: 'apac',
  },
  // 10. Saved — should be excluded
  {
    id: 'job-010',
    date: daysAgo(3),
    status: 'saved',
    role: 'UX Researcher',
    company: 'SavedInc',
    location: 'Remote',
    salary: '',
    ats: 'Lever',
    cv: '',
    portfolio: '',
    link: '',
    notes: '',
    source: 'auto',
    area: 'emea',
  },
  // 11. Skipped — should be excluded
  {
    id: 'job-011',
    date: daysAgo(12),
    status: 'skipped',
    role: 'Interaction Designer',
    company: 'SkipLtd',
    location: 'Remote',
    salary: '',
    ats: 'Greenhouse',
    cv: '',
    portfolio: '',
    link: '',
    notes: '',
    area: 'americas',
  },
  // 12. Ghosted status explicitly
  {
    id: 'job-012',
    date: daysAgo(60),
    status: 'ghosted',
    role: 'Design Systems Lead',
    company: 'SilentCorp',
    location: 'Remote',
    salary: '110k',
    ats: 'Workable',
    cv: 'cvflo.pdf',
    portfolio: 'https://floriangouloubi.com',
    link: 'https://silentcorp.com/jobs/12',
    notes: 'Never heard back',
    source: 'auto',
    area: 'apac',
  },
  // 13. Submitted 65 days ago, no events — max ghost probability
  {
    id: 'job-013',
    date: daysAgo(65),
    status: 'submitted',
    role: 'Principal Designer',
    company: 'AncientCorp',
    location: 'Remote',
    salary: '140k',
    ats: 'Workable',
    cv: 'cvflo.pdf',
    portfolio: 'https://floriangouloubi.com',
    link: 'https://ancientcorp.com/jobs/13',
    notes: 'Applied long ago, lettre de motivation sent',
    source: 'auto',
    area: 'apac',
  },
  // 14. Withdrawn
  {
    id: 'job-014',
    date: daysAgo(18),
    status: 'withdrawn',
    role: 'UX Designer',
    company: 'WithdrawnInc',
    location: 'Manila',
    salary: '70k',
    ats: 'Recruitee',
    cv: 'cvflo.pdf',
    portfolio: '',
    link: 'https://withdrawninc.com/jobs/14',
    notes: 'Position not a good fit',
    source: 'manual',
    area: 'apac',
  },
  // 15. Submitted 22 days ago — just over ghost threshold, no events
  {
    id: 'job-015',
    date: daysAgo(22),
    status: 'submitted',
    role: 'Design Ops Manager',
    company: 'EdgeCase Ltd',
    location: 'Remote',
    salary: '',
    ats: 'Lever',
    cv: 'no',
    portfolio: 'no',
    link: '',
    notes: '',
    source: 'auto',
    area: 'emea',
  },
  // 16. Challenge status
  {
    id: 'job-016',
    date: daysAgo(14),
    status: 'challenge',
    role: 'Product Designer',
    company: 'ChallengeCo',
    location: 'Sydney',
    salary: '100k',
    ats: 'Greenhouse',
    cv: 'cvflo.pdf',
    portfolio: 'https://floriangouloubi.com',
    link: 'https://challengeco.com/jobs/16',
    notes: 'Design challenge received',
    source: 'auto',
    area: 'apac',
    events: [
      {
        id: 'evt-005',
        date: daysAgo(10),
        type: 'design_challenge',
        person: 'Hiring Manager',
        notes: 'Take-home challenge',
        outcome: 'waiting',
        createdAt: daysAgo(10),
      },
    ],
  },
  // 17. Negotiation
  {
    id: 'job-017',
    date: daysAgo(45),
    status: 'negotiation',
    role: 'Lead Designer',
    company: 'NegotiateCo',
    location: 'Kuala Lumpur',
    salary: '115k',
    ats: 'Lever',
    cv: 'cvflo.pdf',
    portfolio: 'https://floriangouloubi.com',
    link: 'https://negotiateco.com/jobs/17',
    notes: 'Salary negotiation in progress',
    source: 'manual',
    area: 'apac',
    lastContactDate: daysAgo(3),
  },
  // 18. Submitted with minimal data — no CV, no portfolio, no salary, no link, no notes
  {
    id: 'job-018',
    date: daysAgo(8),
    status: 'submitted',
    role: 'Junior Designer',
    company: 'MinimalData',
    location: '',
    salary: '',
    ats: 'Greenhouse',
    cv: '',
    portfolio: '',
    link: '',
    notes: '',
    source: 'auto',
    area: '',
  },
  // 19. Submitted recently, fully filled out — max quality
  {
    id: 'job-019',
    date: daysAgo(2),
    status: 'submitted',
    role: 'Senior Product Designer',
    company: 'PerfectApp',
    location: 'Singapore',
    salary: '120k',
    ats: 'Lever',
    cv: 'cvflo.pdf',
    portfolio: 'https://floriangouloubi.com',
    link: 'https://perfectapp.com/jobs/19',
    notes: 'Excellent match, included cover letter and motivation summary',
    source: 'manual',
    area: 'apac',
  },
  // 20. Submitted 21 days ago exactly — boundary for ghost threshold
  {
    id: 'job-020',
    date: daysAgo(21),
    status: 'submitted',
    role: 'UX/UI Designer',
    company: 'BoundaryInc',
    location: 'Remote',
    salary: '85k',
    ats: 'Workable',
    cv: 'cvflo.pdf',
    portfolio: '',
    link: 'https://boundaryinc.com/jobs/20',
    notes: 'Applied on threshold day',
    source: 'auto',
    area: 'apac',
  },
]

/**
 * Helper: create a minimal Job with overrides.
 */
export function makeJob(overrides: Partial<Job> = {}): Job {
  return {
    id: `job-${Math.random().toString(36).slice(2, 8)}`,
    date: daysAgo(5),
    status: 'submitted',
    role: 'Designer',
    company: 'TestCo',
    location: 'Remote',
    salary: '',
    ats: 'Greenhouse',
    cv: '',
    portfolio: '',
    link: '',
    notes: '',
    ...overrides,
  }
}
